#:schema https://json.schemastore.org/any.json

env_files = []
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  stop_delay = 500
  bin = "tmp\\main.exe"
  cmd = "go build -gcflags='all=-N -l' -o ./tmp/main.exe ./app"
  delay = 1000
  entrypoint = ["tmp\\main.exe"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "app/vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  log = "build-errors.log"
  post_cmd = []
  pre_cmd = []
[env]
  AIR_MODE = "true"
  CGO_ENABLED = "0"